---
- name: browser slice
  template: 
    src: user-browsers.slice
    dest: /etc/systemd/system/user-browsers.slice 
    owner: root
    group: root
    mode:  0644
  notify: reload user-browsers

- name: electron slice
  template: 
    src: user-electron.slice
    dest: /etc/systemd/system/user-electron.slice 
    owner: root
    group: root
    mode:  0644
  notify: reload user-electron

- name: Firefox Update
  replace:
    path: /usr/share/applications/firefox.desktop
    regexp: Exec=firefox[ $]?
    replace: "Exec=systemd-run --slice user-browsers.slice --user --scope /usr/bin/firefox "

- name: Chrome Update
  replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: Exec=/usr/bin/google-chrome-stable[ $]?
    replace: "Exec=systemd-run --slice user-browsers.slice --user --scope /usr/bin/google-chrome-stable "

- name: Slack Update
  replace:
    path: /usr/share/applications/slack.desktop
    regexp: Exec=/usr/bin/slack[ $]?
    replace: "Exec=systemd-run --slice user-electron.slice --user --scope /usr/bin/slack "

#- name: Install libselinux-python
#  yum: name=libselinux-python state=present
#
#- name: Reload ansible_facts
#  setup:
